name: Deploy .NET Application to Windows EC2 with IIS

on:
  push:
    branches:
      - main  # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: windows-latest  # GitHub hosted runner for Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Replace with your .NET version
          
      - name: Navigate to project directory and publish
        run: |
          cd DummyDotNetApp  # Navigate to the project directory
          dotnet restore DummyDotNetApp.csproj  # Specify the .csproj file explicitly
          dotnet publish DummyDotNetApp.csproj -c Release -o ./publish  # Specify the .csproj file explicitly

      - name: Setup SSH to Windows EC2 and Deploy
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # GitHub secret containing private key
          
      - name: Deploy to Windows EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} administrator@${{ secrets.EC2_PUBLIC_IP }} powershell -Command "
            # IIS deployment script
            New-Item -Path 'C:\inetpub\wwwroot\DummyDotNetApp' -ItemType Directory -Force
            Copy-Item -Path './publish/*' -Destination 'C:\inetpub\wwwroot\DummyDotNetApp' -Recurse
            iisreset
          "
