name: Deploy to IIS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Publish .NET Application
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ./publish

    - name: Configure SSH Key
      run: |
        mkdir C:\Users\runneradmin\.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > C:\Users\runneradmin\.ssh\id_rsa
        chmod 600 C:\Users\runneradmin\.ssh\id_rsa

    - name: Add Host to Known Hosts
      run: |
        ssh-keyscan -H <EC2_PUBLIC_IP> >> C:\Users\runneradmin\.ssh\known_hosts

    - name: Deploy Application via SSH
      run: |
        ssh -v -o StrictHostKeyChecking=no -i C:/Users/runneradmin/.ssh/id_rsa administrator@<EC2_PUBLIC_IP> powershell -Command "
        New-Item -Path 'C:\inetpub\wwwroot\DummyDotNetApp' -ItemType Directory -Force;
        Copy-Item -Path 'C:\actions-runner\_work\DummyDotNetApp\publish\*' -Destination 'C:\inetpub\wwwroot\DummyDotNetApp' -Recurse;
        iisreset;
        "
      env:
        DOTNET_ROOT: C:\Program Files\dotnet
