name: Deploy .NET Application to Windows EC2

on:
  push:
    branches:
      - main  # Adjust the branch as necessary

jobs:
  deploy:
    runs-on: windows-latest  # This uses a GitHub-hosted Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Replace with your target .NET version

      - name: Publish .NET Application
        run: |
          # Ensure the project directory exists
          if (!(Test-Path -Path './DummyDotNetApp')) {
            Write-Host "Error: 'DummyDotNetApp' directory does not exist."
            exit 1
          }
          cd DummyDotNetApp  # Navigate to the project directory
          dotnet restore DummyDotNetApp.csproj
          dotnet publish DummyDotNetApp.csproj -c Release -o ./publish  # Publish to ./publish directory

      - name: Install sshpass (for password-based authentication)
        run: |
          choco install sshpass  # Install sshpass on the GitHub runner

      - name: Deploy to Windows EC2 via SSH (Password-based)
        run: |
          echo "Starting SSH deployment..."
          sshpass -p "${{ secrets.EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no administrator@${{ secrets.EC2_PUBLIC_IP }} powershell -Command "
          New-Item -Path 'C:\inetpub\wwwroot\DummyDotNetApp' -ItemType Directory -Force
          Copy-Item -Path './publish/*' -Destination 'C:\inetpub\wwwroot\DummyDotNetApp' -Recurse
          iisreset
          "
